SELECT
  TO_HEX(SHA256(CONCAT('order_item|', order_id, '|', sku_id))) AS order_item_key,
  order_id,
  TO_HEX(SHA256(CONCAT('sku|', sku_id))) AS sku_key,
  TO_HEX(SHA256(CONCAT('product|', product_id))) AS product_key,
  TO_HEX(SHA256(CONCAT('channel|', order_channel))) AS channel_key,
  IF(creator_token IS NULL, NULL, TO_HEX(SHA256(CONCAT('creator|', creator_token)))) AS creator_key,
  TO_HEX(SHA256(CONCAT('payment_method|', payment_method))) AS payment_method_key,
  order_status,
  quantity,
  unit_original_price,
  subtotal_before_discount,
  total_discount,
  subtotal_after_discount,
  order_amount,
  refund_amount,
  created_at,
  CAST(FORMAT_DATE('%Y%m%d', DATE(created_at)) AS INT64) AS date_key,
  DATE(created_at) AS order_date,
  fulfillment_type,
  shipping_provider,
  order_channel,
  creator_token,
  buyer_token,
  region_code,
  package_token
FROM {{ source('staging', 'stg_orders') }}
